name: dennyink.com
favicon: null
layout_spectrum: 0.50483
typography_spectrum: 0.50049
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Denny, ink.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: dennyink
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2b26'
    - '#c33521'
    - '#e0ded2'
    - '#ec7459'
    - '#a39a91'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
