name: dennyink.com
favicon: null
layout_spectrum: 0.12427414325065911
typography_spectrum: 0.7330782418139279
title: 'Denny, ink. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: dennyink
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#abb6c0'
    - '#ae937a'
    - '#1a1005'
    - '#546e80'
    - '#e2ae71'
  brandStrength: 0.4305726857855916
  lightness: 0.42403366207145154
  saturation: 0.3160599081311375
  rhythmicContrast: 0.5936745039653033
purpose: []
