name: dennyink.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61169
title: 'Denny, ink. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: dennyink
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#abb6c0'
    - '#ae937a'
    - '#1a1005'
    - '#546e80'
    - '#e2ae71'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
