typography_spectrum: 0.8136201
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
title: 'Denny, ink. '
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.4375
  rhythmicContrast: 0.75
  brandColors:
    - '#91BDE8'
    - '#021F80'
    - '#9A020C'
    - '#05040D'
    - '#6E7791'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: dennyink
  facebook: null
name: dennyink.com
