name: dennyink.com
favicon: null
layout_spectrum: 0.12427414325065911
typography_spectrum: 0.7330782418139279
title: 'Denny, ink. Brand Communication'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4305726857855916
  lightness: 0.42403366207145154
  saturation: 0.3160599081311375
  rhythmicContrast: 0.5936745039653033
purpose: []
